# Generated by Django 2.2 on 2020-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=45)),
                ('network', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
